package kubernetes

var fields = []string{
	"DiscoveryClient",
	"admissionregistrationV1alpha1",
	"admissionregistrationV1beta1",
	"appsV1beta1",
	"appsV1beta2",
	"appsV1",
	"authenticationV1",
	"authenticationV1beta1",
	"authorizationV1",
	"authorizationV1beta1",
	"autoscalingV1",
	"autoscalingV2beta1",
	"batchV1",
	"batchV1beta1",
	"batchV2alpha1",
	"certificatesV1beta1",
	"coreV1",
	"eventsV1beta1",
	"extensionsV1beta1",
	"networkingV1",
	"policyV1beta1",
	"rbacV1",
	"rbacV1beta1",
	"rbacV1alpha1",
	"schedulingV1alpha1",
	"schedulingV1beta1",
	"settingsV1alpha1",
	"storageV1beta1",
	"storageV1",
	"storageV1alpha1",
}
